const questionsData = [
  {
    id: 1,
    topic: "Math",
    difficulty: "easy",
    question: "What is 8 + 7?",
    options: ["14", "15", "16", "13"],
    answer: "15",
    marks: 1,
    explanation: "8 + 7 = 15.",
  },
  {
    id: 2,
    topic: "Math",
    difficulty: "medium",
    question: "What is the square root of 144?",
    options: ["10", "11", "12", "14"],
    answer: "12",
    marks: 2,
    explanation: "12 × 12 = 144.",
  },
  {
    id: 3,
    topic: "Logic",
    difficulty: "easy",
    question: "If all dogs are animals and Rex is a dog, what is Rex?",
    options: ["Human", "Animal", "Reptile", "Insect"],
    answer: "Animal",
    marks: 1,
    explanation: "All dogs are animals; Rex is a dog.",
  },
  {
    id: 4,
    topic: "Logic",
    difficulty: "medium",
    question: "Which number completes the pattern: 2, 4, 8, 16, ___?",
    options: ["20", "32", "30", "24"],
    answer: "32",
    marks: 2,
    explanation: "Each number doubles.",
  },
  {
    id: 5,
    topic: "Science",
    difficulty: "easy",
    question: "What planet is known as the Red Planet?",
    options: ["Mars", "Earth", "Venus", "Jupiter"],
    answer: "Mars",
    marks: 1,
    explanation: "Mars appears red due to iron oxide.",
  },
  //{
  //  id: 6,
  //  topic: "Science",
  //  difficulty: "medium",
  //  question: "What gas do plants absorb for photosynthesis?",
  //  options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Helium"],
  //  answer: "Carbon Dioxide",
  //  marks: 2,
  //  explanation: "Plants absorb CO₂.",
  //},
  //{
  //  id: 7,
  //  topic: "Geography",
  //  difficulty: "easy",
  //  question: "Which continent is the Sahara Desert located in?",
  //  options: ["Asia", "Africa", "Europe", "Australia"],
  //  answer: "Africa",
  //  marks: 1,
  //  explanation: "Sahara is the largest hot desert.",
  //},
  //{
  //  id: 8,
  //  topic: "Geography",
  //  difficulty: "medium",
  //  question: "Which country has the largest population?",
  //  options: ["India", "USA", "China", "Russia"],
  //  answer: "China",
  //  marks: 2,
  //  explanation: "China currently has the highest population.",
  //},
  //{
  //  id: 9,
  //  topic: "History",
  //  difficulty: "easy",
  //  question: "Who was the first President of the United States?",
  //  options: [
  //    "Abraham Lincoln",
  //    "George Washington",
  //    "Thomas Jefferson",
  //    "John Adams",
  //  ],
  //  answer: "George Washington",
  //  marks: 1,
  //},
  //{
  //  id: 10,
  //  topic: "History",
  //  difficulty: "medium",
  //  question: "In which year did World War II end?",
  //  options: ["1942", "1945", "1939", "1950"],
  //  answer: "1945",
  //  marks: 2,
  //},

  //// ---- Continue generating 40 more ----

  //{
  //  id: 11,
  //  topic: "Math",
  //  difficulty: "easy",
  //  question: "What is 9 × 6?",
  //  options: ["54", "48", "57", "64"],
  //  answer: "54",
  //  marks: 1,
  //},
  //{
  //  id: 12,
  //  topic: "Math",
  //  difficulty: "hard",
  //  question: "Solve: 3x + 12 = 33",
  //  options: ["7", "9", "11", "13"],
  //  answer: "7",
  //  marks: 3,
  //},
  //{
  //  id: 13,
  //  topic: "Math",
  //  difficulty: "medium",
  //  question: "What is 25% of 200?",
  //  options: ["50", "60", "40", "55"],
  //  answer: "50",
  //  marks: 2,
  //},
  //{
  //  id: 14,
  //  topic: "Logic",
  //  difficulty: "medium",
  //  question: "Which shape has 4 equal sides?",
  //  options: ["Rectangle", "Square", "Triangle", "Trapezium"],
  //  answer: "Square",
  //  marks: 2,
  //},
  //{
  //  id: 15,
  //  topic: "Logic",
  //  difficulty: "hard",
  //  question: "Which word does NOT belong: Cat, Dog, Cow, Eagle?",
  //  options: ["Cat", "Dog", "Cow", "Eagle"],
  //  answer: "Eagle",
  //  marks: 3,
  //  explanation: "Eagle is a bird; others are mammals.",
  //},
  //{
  //  id: 16,
  //  topic: "Science",
  //  difficulty: "easy",
  //  question: "What is H₂O commonly known as?",
  //  options: ["Salt", "Water", "Oxygen", "Hydrogen"],
  //  answer: "Water",
  //  marks: 1,
  //},
  //{
  //  id: 17,
  //  topic: "Science",
  //  difficulty: "hard",
  //  question: "What is the powerhouse of the cell?",
  //  options: ["Nucleus", "Mitochondria", "Ribosome", "Golgi Apparatus"],
  //  answer: "Mitochondria",
  //  marks: 3,
  //},
  //{
  //  id: 18,
  //  topic: "Science",
  //  difficulty: "medium",
  //  question: "What force keeps us grounded on Earth?",
  //  options: ["Magnetism", "Gravity", "Pressure", "Friction"],
  //  answer: "Gravity",
  //  marks: 2,
  //},
  //{
  //  id: 19,
  //  topic: "Geography",
  //  difficulty: "medium",
  //  question: "What is the longest river in the world?",
  //  options: ["Yangtze", "Amazon", "Nile", "Congo"],
  //  answer: "Nile",
  //  marks: 2,
  //},
  //{
  //  id: 20,
  //  topic: "Geography",
  //  difficulty: "hard",
  //  question: "Which country has the most natural lakes?",
  //  options: ["USA", "Canada", "Russia", "Brazil"],
  //  answer: "Canada",
  //  marks: 3,
  //},
  //{
  //  id: 21,
  //  topic: "History",
  //  difficulty: "easy",
  //  question: "Which ancient civilization built the pyramids?",
  //  options: ["Romans", "Greeks", "Egyptians", "Mayans"],
  //  answer: "Egyptians",
  //  marks: 1,
  //},
  //{
  //  id: 22,
  //  topic: "History",
  //  difficulty: "medium",
  //  question: "The Roman Empire fell in what year?",
  //  options: ["476 AD", "300 AD", "1200 AD", "999 AD"],
  //  answer: "476 AD",
  //  marks: 2,
  //},
  //{
  //  id: 23,
  //  topic: "English",
  //  difficulty: "easy",
  //  question: "Choose the correct spelling:",
  //  options: ["Definately", "Definitely", "Definetely", "Defanatly"],
  //  answer: "Definitely",
  //  marks: 1,
  //},
  //{
  //  id: 24,
  //  topic: "English",
  //  difficulty: "medium",
  //  question: "What is the synonym of 'rapid'?",
  //  options: ["Slow", "Fast", "Calm", "Weak"],
  //  answer: "Fast",
  //  marks: 2,
  //},
  //{
  //  id: 25,
  //  topic: "English",
  //  difficulty: "hard",
  //  question: "Which is an antonym of 'scarce'?",
  //  options: ["Plentiful", "Rare", "Limited", "Few"],
  //  answer: "Plentiful",
  //  marks: 3,
  //},
  //{
  //  id: 26,
  //  topic: "Tech",
  //  difficulty: "easy",
  //  question: "What does CPU stand for?",
  //  options: [
  //    "Central Processing Unit",
  //    "Computer Power Unit",
  //    "Control Process Utility",
  //    "Center Power Unit",
  //  ],
  //  answer: "Central Processing Unit",
  //  marks: 1,
  //},
  //{
  //  id: 27,
  //  topic: "Tech",
  //  difficulty: "medium",
  //  question: "Which language is primarily used for web styling?",
  //  options: ["HTML", "CSS", "Python", "SQL"],
  //  answer: "CSS",
  //  marks: 2,
  //},
  //{
  //  id: 28,
  //  topic: "Tech",
  //  difficulty: "medium",
  //  question: "What does HTTP stand for?",
  //  options: [
  //    "Hypertext Transfer Protocol",
  //    "High Transfer Text Process",
  //    "Hyperlink Test Protocol",
  //    "High Transmission Text Port",
  //  ],
  //  answer: "Hypertext Transfer Protocol",
  //  marks: 2,
  //},
  //{
  //  id: 29,
  //  topic: "Tech",
  //  difficulty: "hard",
  //  question: "Which data structure uses FIFO?",
  //  options: ["Stack", "Queue", "Tree", "Graph"],
  //  answer: "Queue",
  //  marks: 3,
  //},
  //{
  //  id: 30,
  //  topic: "Logic",
  //  difficulty: "easy",
  //  question: "Which number is missing: 5, 10, 15, 20, ___?",
  //  options: ["30", "35", "25", "28"],
  //  answer: "25",
  //  marks: 1,
  //},
  //{
  //  id: 31,
  //  topic: "Logic",
  //  difficulty: "medium",
  //  question: "Find the odd one out: 2, 4, 8, 9, 16",
  //  options: ["8", "4", "9", "16"],
  //  answer: "9",
  //  marks: 2,
  //},
  //{
  //  id: 32,
  //  topic: "Logic",
  //  difficulty: "hard",
  //  question: "If A = 1, B = 2, C = 3. What is D + F?",
  //  options: ["9", "8", "6", "10"],
  //  answer: "10",
  //  marks: 3,
  //  explanation: "D=4, F=6 → 4+6=10",
  //},
  //{
  //  id: 33,
  //  topic: "Science",
  //  difficulty: "easy",
  //  question: "Which organ pumps blood?",
  //  options: ["Heart", "Brain", "Liver", "Lungs"],
  //  answer: "Heart",
  //  marks: 1,
  //},
  //{
  //  id: 34,
  //  topic: "Science",
  //  difficulty: "medium",
  //  question: "What is Earth's only natural satellite?",
  //  options: ["Mars", "Sun", "Moon", "Venus"],
  //  answer: "Moon",
  //  marks: 2,
  //},
  //{
  //  id: 35,
  //  topic: "Science",
  //  difficulty: "hard",
  //  question: "What is the chemical symbol for Gold?",
  //  options: ["Gd", "Au", "Ag", "Go"],
  //  answer: "Au",
  //  marks: 3,
  //},
  //{
  //  id: 36,
  //  topic: "Geography",
  //  difficulty: "easy",
  //  question: "What is the capital of Japan?",
  //  options: ["Osaka", "Kyoto", "Tokyo", "Nagoya"],
  //  answer: "Tokyo",
  //  marks: 1,
  //},
  //{
  //  id: 37,
  //  topic: "Geography",
  //  difficulty: "medium",
  //  question: "What ocean is the largest?",
  //  options: ["Atlantic", "Indian", "Pacific", "Arctic"],
  //  answer: "Pacific",
  //  marks: 2,
  //},
  //{
  //  id: 38,
  //  topic: "Geography",
  //  difficulty: "hard",
  //  question: "Mount Everest is located on the border of which two countries?",
  //  options: [
  //    "China & India",
  //    "Nepal & China",
  //    "India & Nepal",
  //    "Pakistan & India",
  //  ],
  //  answer: "Nepal & China",
  //  marks: 3,
  //},
  //{
  //  id: 39,
  //  topic: "History",
  //  difficulty: "easy",
  //  question: "Which war ended with the Treaty of Versailles?",
  //  options: ["WW1", "WW2", "Cold War", "Vietnam War"],
  //  answer: "WW1",
  //  marks: 1,
  //},
  //{
  //  id: 40,
  //  topic: "History",
  //  difficulty: "medium",
  //  question: "Who discovered electricity?",
  //  options: [
  //    "Benjamin Franklin",
  //    "Thomas Edison",
  //    "Nikola Tesla",
  //    "James Maxwell",
  //  ],
  //  answer: "Benjamin Franklin",
  //  marks: 2,
  //},
  //{
  //  id: 41,
  //  topic: "English",
  //  difficulty: "easy",
  //  question: "Which is a verb?",
  //  options: ["Run", "Blue", "Tall", "Happiness"],
  //  answer: "Run",
  //  marks: 1,
  //},
  //{
  //  id: 42,
  //  topic: "English",
  //  difficulty: "medium",
  //  question: "What is the plural of 'child'?",
  //  options: ["childs", "childer", "children", "childes"],
  //  answer: "children",
  //  marks: 2,
  //},
  //{
  //  id: 43,
  //  topic: "English",
  //  difficulty: "hard",
  //  question: "Which sentence is correctly punctuated?",
  //  options: [
  //    "Its raining outside.",
  //    "It's raining outside.",
  //    "Its' raining outside.",
  //    "Its raining, outside.",
  //  ],
  //  answer: "It's raining outside.",
  //  marks: 3,
  //},
  //{
  //  id: 44,
  //  topic: "Tech",
  //  difficulty: "easy",
  //  question: "Which company created Android?",
  //  options: ["Apple", "Google", "Microsoft", "IBM"],
  //  answer: "Google",
  //  marks: 1,
  //},
  //{
  //  id: 45,
  //  topic: "Tech",
  //  difficulty: "medium",
  //  question: "Which version control system is most widely used?",
  //  options: ["SVN", "Mercurial", "Git", "CVS"],
  //  answer: "Git",
  //  marks: 2,
  //},
  //{
  //  id: 46,
  //  topic: "Tech",
  //  difficulty: "hard",
  //  question: "What does 'API' stand for?",
  //  options: [
  //    "Application Programming Interface",
  //    "Advanced Program Interaction",
  //    "Automated Program Integration",
  //    "Applied Process Information",
  //  ],
  //  answer: "Application Programming Interface",
  //  marks: 3,
  //},
  //{
  //  id: 47,
  //  topic: "Logic",
  //  difficulty: "easy",
  //  question: "Which number is an even number?",
  //  options: ["7", "11", "16", "25"],
  //  answer: "16",
  //  marks: 1,
  //},
  //{
  //  id: 48,
  //  topic: "Logic",
  //  difficulty: "medium",
  //  question: "If today is Monday, what day will it be in 10 days?",
  //  options: ["Saturday", "Sunday", "Wednesday", "Friday"],
  //  answer: "Thursday",
  //  marks: 2,
  //  explanation: "10 days after Monday → Thursday.",
  //},
  //{
  //  id: 49,
  //  topic: "Logic",
  //  difficulty: "hard",
  //  question: "Which comes next in the sequence: A, C, F, J, O, ___?",
  //  options: ["S", "U", "T", "V"],
  //  answer: "U",
  //  marks: 3,
  //  explanation: "Positions: +2, +3, +4, +5, next is +6 → O(15)+6=21 → U.",
  //},
  //{
  //  id: 50,
  //  topic: "Science",
  //  difficulty: "medium",
  //  question: "What is the boiling point of water at sea level?",
  //  options: ["80°C", "90°C", "100°C", "120°C"],
  //  answer: "100°C",
  //  marks: 2,
  //},
];

export const quizQuestions = {
	data: () =>
  count: questionsData.length,
  currentIndex: 0,
  all: () => questionsData,
  current: () => {
    if (quizQuestions.currentIndex >= quizQuestions.count) {
      return null;
    }
    const question = questionsData[quizQuestions.currentIndex];
    question.number = quizQuestions.currentIndex + 1;
    return question;
  },

  previous: () => {
    if (quizQuestions.currentIndex > 0) {
      quizQuestions.currentIndex = quizQuestions.currentIndex - 1;
    }
  },
  next: () => {
    const questionsCount = questionsData.length;
    if (quizQuestions.currentIndex < questionsCount - 1) {
      quizQuestions.currentIndex = quizQuestions.currentIndex + 1;
    }
  },
  get: (id) => {
    const questions = quizQuestions.all();
    const question = questions.find((q) => q.id == id);
    return question;
  },
};
